a few more mappings, some client and screen stuff, some util stuff
Copetan/feather-mappings pull request #36
Opened 2021-12-29 17:38 UTC by SRAZKVT

2021-12-29 17:43 UTC, KayleighWasTaken requested changes
- [x] `field_10136` is a `static final` and as such should be in `UPPER_SNAKE_CASE`, it is also convention to name the main (or only) texture used by a class `TEXTURE`. Recommend to revert change.
- [x] `field_10137` should be named `parentBlockEntity` by convention, as this is done in all `Screen` classes which have a block entity. Recommend reversion.

Everything else looks good though.

2021-12-29 17:59 UTC, KayleighWasTaken approved these changes
Looks good now :+1:

2021-12-29 18:15 UTC, KayleighWasTaken commented
Uhh, apparently I already mapped `class_2300` to `EnchantingTableScreen` in my PR. I'm unsure what to do about this, I think your mappings for it are more complete so they should probably be merged over mine.

Also you forgot to `UPPER_SNAKE_CASE` two `static final`s in there: `enchantingTableTexture` => `TEXTURE` (or similar, I called it `SCREEN_TEXTURE`), and `enchantingTableBookTexture` => `BOOK_TEXTURE` (or similar).

2021-12-30 03:39 UTC, Copetan approved these changes

2021-12-30 03:51 UTC, merged